version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: wegift-frontend
        ports:
            - "3000:80"
        restart: unless-stopped
